Mission2Assignment/Models/GradesModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mission3Assignment.Models
{
    public class GradesModel
    {
        [Required]
            public int assignment { get; set; }
            public int project { get; set; }
            public int quiz { get; set; }
            public int exam { get; set; }
            public int intex { get; set; }
    }
}

Mission2Assignment/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission3Assignment.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Mission3Assignment.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Grades()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Grades(GradesModel model)
        {
            return View();
        }
    }
}

Mission2Assignment/Views/Blah/Grades.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grades";
}

@model GradesModel;
<h2>Grade Calculator:</h2>
<form method="post">
    <label>Assignments(55%):</label>
    <input id="txtAssignment" asp-for="assignment" /> <br />
    <label>Group Project(5%):</label>
    <input id="txtproject" asp-for="project"/> <br />
    <label>Quizzes(10%):</label>
    <input id="txtquizzes" asp-for="quiz"/><br />
    <label>Exams(20%)</label>
    <input id="txtexams" asp-for="exam" /><br />
    <label>INTEX(10%)</label>
    <input id="txtintex" asp-for="intex"/><br />
    <input id="btnsend" type="submit" value="Submit" />

    <div asp-validation-summary="All"></div>
</form>

Mission2Assignment/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Landon";
}



<h1>Landon Maxfield</h1>
<img id="picTrack" src="img/track.jpeg" style="width:600px; height:auto;" />
<p>This year in IS 413 I hope to learn how to quickly and effectively create web apps. I hope to become proficient at web development and become confident in my abilities.</p>
<br />

<p>My top 3 jobs when I graduate</p>
<ul>
    <li>Stay at home dad</li>
    <li>Data analyst</li>
    <li>Professional Track runer</li>
</ul>

Mission2Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/css/bootstrap.rtl.css" />
    <link href="~/css/default.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="Grades">Grades</a>
    </nav>
    <div>
        @RenderBody()
    </div>

    <footer>
        This is the footer
    </footer>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
    <script src="~/js/grade.js"></script>
</body>
</html>